spring:
  datasource:
    url: jdbc:h2:file:./data/db
    driverClassName: org.h2.Driver
    username: sa
    password:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
file:
  upload:
    dir: tmp